import { pgTable, uuid, text, numeric, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";

export const profiles = pgTable("profiles", {
  id: uuid("id").primaryKey(),
  email: text("email").notNull(),
  fullName: text("full_name"),
  subscriptionTier: text("subscription_tier").notNull().default("free"),
  subscriptionStatus: text("subscription_status").notNull().default("active"),
  telegramChatId: text("telegram_chat_id"),
  telegramAlertsEnabled: boolean("telegram_alerts_enabled").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const mt5Accounts = pgTable("mt5_accounts", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  accountName: text("account_name").notNull(),
  accountNumber: text("account_number").notNull(),
  accountPassword: text("account_password"),
  brokerName: text("broker_name").notNull(),
  brokerServer: text("broker_server"),
  platform: text("platform").notNull().default("MT5"),
  connectionType: text("connection_type").notNull().default("metaapi"),
  metaapiAccountId: text("metaapi_account_id").unique(),
  connectionStatus: text("connection_status").notNull().default("CONNECTING"),
  accountType: text("account_type").notNull().default("evaluation"),
  accountCurrency: text("account_currency").notNull().default("USD"),
  currency: text("currency").notNull().default("USD"),
  initialBalance: numeric("initial_balance", { precision: 15, scale: 2 }).notNull().default("0"),
  balance: numeric("balance", { precision: 15, scale: 2 }).notNull().default("0"),
  equity: numeric("equity", { precision: 15, scale: 2 }).notNull().default("0"),
  currentBalance: numeric("current_balance", { precision: 15, scale: 2 }).notNull().default("0"),
  currentEquity: numeric("current_equity", { precision: 15, scale: 2 }).notNull().default("0"),
  highWaterMark: numeric("high_water_mark", { precision: 15, scale: 2 }).notNull().default("0"),
  maxTotalDrawdownPct: numeric("max_total_drawdown_pct", { precision: 5, scale: 2 }).notNull().default("10"),
  maxDailyDrawdownPct: numeric("max_daily_drawdown_pct", { precision: 5, scale: 2 }).notNull().default("5"),
  dailyStartingBalance: numeric("daily_starting_balance", { precision: 15, scale: 2 }),
  drawdownType: text("drawdown_type").notNull().default("trailing"),
  drawdownStatus: text("drawdown_status").notNull().default("SAFE"),
  isActive: boolean("is_active").notNull().default(true),
  isBreached: boolean("is_breached").notNull().default(false),
  lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }).defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
});

export const trades = pgTable("trades", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  accountId: uuid("account_id").references(() => mt5Accounts.id, { onDelete: "set null" }),
  dealId: text("deal_id").unique(),
  symbol: text("symbol").notNull(),
  action: text("action").notNull(),
  openPrice: numeric("open_price", { precision: 15, scale: 5 }).notNull(),
  closePrice: numeric("close_price", { precision: 15, scale: 5 }),
  stopLoss: numeric("stop_loss", { precision: 15, scale: 5 }),
  takeProfit: numeric("take_profit", { precision: 15, scale: 5 }),
  volume: numeric("volume", { precision: 10, scale: 2 }).notNull(),
  pnl: numeric("pnl", { precision: 15, scale: 2 }).default("0.00"),
  status: text("status").default("OPEN"),
  notes: text("notes"),
  tags: text("tags").array(),
  openTime: timestamp("open_time", { withTimezone: true }).defaultNow(),
  closeTime: timestamp("close_time", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});

export const calculatorPresets = pgTable("calculator_presets", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: uuid("user_id").notNull().references(() => profiles.id, { onDelete: "cascade" }),
  presetName: text("preset_name").notNull(),
  defaultRiskPct: numeric("default_risk_pct", { precision: 5, scale: 2 }).default("1.00"),
  defaultStopLossPips: numeric("default_stop_loss_pips", { precision: 6, scale: 1 }).default("15.0"),
  pairSpecifications: jsonb("pair_specifications").default({ EURUSD: 10, GBPUSD: 10, XAUUSD: 100 }),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
