"use client";

import { ExternalLink, LockKeyhole } from "lucide-react";
import type { FirmEvaluation } from "@/lib/firm-fit/evaluator";

interface MatrixGridProps { results: FirmEvaluation[]; onDetails: (result: FirmEvaluation) => void; }
function badge(result: FirmEvaluation) { return result.matchPercentage >= 80 ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-300" : result.matchPercentage >= 50 ? "border-amber-400/30 bg-amber-400/10 text-amber-300" : "border-rose-400/30 bg-rose-400/10 text-rose-300"; }
export function MatrixGrid({ results, onDetails }: MatrixGridProps) {
  return <div className="grid gap-5 lg:grid-cols-2">{results.map((result) => { const limit = result.firm.rules.maxTotalDrawdown; const gauge = Math.min(100, (result.userMaxTotalDD / Math.max(limit, 0.01)) * 100); return <article key={result.firm.id} className="rounded-2xl border border-indigo-500/20 bg-slate-900/75 p-5 shadow-xl shadow-indigo-950/20"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-500/15 text-lg font-black text-cyan-300">{result.firm.name.slice(0, 1)}</div><h2 className="text-lg font-bold text-white">{result.firm.name}</h2></div><p className="mt-3 text-sm text-slate-400">{result.status.replace("_", " ")}</p></div><span className={`rounded-full border px-3 py-1 text-lg font-black ${badge(result)}`}>{result.matchPercentage}%</span></div><div className="mt-5"><div className="flex justify-between text-xs text-slate-400"><span>Your max DD: {result.userMaxTotalDD.toFixed(2)}%</span><span>Firm limit: {limit.toFixed(2)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full ${gauge >= 80 ? "bg-rose-500" : gauge >= 50 ? "bg-amber-400" : "bg-emerald-400"}`} style={{ width: `${gauge}%` }} /></div></div><div className="mt-4 flex flex-wrap gap-2">{result.breaches.slice(0, 3).map((breach) => <span key={breach} className="rounded-full border border-amber-400/20 bg-amber-400/10 px-2.5 py-1 text-[11px] text-amber-200">{breach.includes("weekend") ? "Weekend Holding Violation" : breach.includes("drawdown") ? "Trailing DD Risk" : "Rule Warning"}</span>)}</div><div className="mt-5 flex flex-col gap-2 sm:flex-row"><a href={result.firm.affiliateUrl} target="_blank" rel="noreferrer" className="inline-flex flex-1 items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-cyan-400 to-indigo-400 px-3 py-2.5 text-center text-xs font-black text-slate-950 hover:brightness-110">Get {result.firm.name} Account ({result.firm.discountPercentage}% Off) <ExternalLink className="h-3.5 w-3.5" /></a><button type="button" onClick={() => onDetails(result)} className="rounded-lg border border-slate-700 px-3 py-2.5 text-xs font-bold text-slate-200 hover:border-cyan-400">View Breach Details</button></div></article>; })}</div>;
}
